import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'
import './globals.css'
import NavbarIndex from '@/components/Navbar/Navigation'
const inter = Poppins({ subsets: ['latin'],weight:['400'] })
import {Providers} from "./providers";
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html  lang="en">
      <body className={inter.className}>
        <Providers>
        <NavbarIndex/>
        {children}
        </Providers>
        </body>
    </html>
  )
}
